name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Checkout
        uses: actions/checkout@v1
      - name: Login to Docker Github
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm run start:coverage && docker run -p 11006:11006 ghcr.io/informatique-cdc/ebad/ebad:2.10.0
          wait-on: 'http://localhost:11006/ebad/actuator/health, http://localhost:4200'
          wait-on-timeout: 180
          browser: chrome
          command-prefix: npx
          install-command: npm ci --legacy-peer-deps
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
      - name: SonarCloud Scan
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
